name: anilist_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  #runners
  built_value: ^8.6.3
  built_collection: ^5.1.1

  dio: ^5.3.3
  meta: ^1.10.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7

  #runners
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3

